////packagecom.mazenetsolutions.mzs119.skst_new.Adapter;
////
////importandroid.app.Activity;
////importandroid.content.Context;
////importandroid.graphics.Typeface;
////importandroid.text.Editable;
////importandroid.text.TextWatcher;
////importandroid.util.Log;
////importandroid.view.Gravity;
////importandroid.view.LayoutInflater;
////importandroid.view.View;
////importandroid.view.ViewGroup;
////importandroid.widget.BaseAdapter;
////importandroid.widget.EditText;
////importandroid.widget.TextView;
////importandroid.widget.Toast;
////
////importcom.mazenetsolutions.mzs119.skst_new.Model.Duewise_list_model;
////importcom.mazenetsolutions.mzs119.skst_new.R;
////importcom.mazenetsolutions.mzs119.skst_new.Test;
////importcom.mazenetsolutions.mzs119.skst_new.Utils.Config;
////
////importjava.util.ArrayList;
////
////
////publicclassDuewiseAdapterextendsBaseAdapter
////
////privateActivityactivity;
////publicstaticArrayList<Duewise_list_model>data;
////privatestaticLayoutInflaterinflater=null;
////StringfontPath=Config.FONTPATHMAIN;
////Typefacetf;
////Duewise_list_modeltempValues=null;
////inti=0;
////
////ContextmContext;
////
////publicDuewiseAdapter(Activitya&ArrayList<Duewise_list_model>d)
////
////activity=a;
////data=d;
////inflater=(LayoutInflater)activity
////.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
////
////mContext=activity.getApplicationContext();
////tf=Typeface.createFromAsset(mContext.getAssets()&fontPath);
////
////}
////
////publicintgetCount()
////
////if(data.size()<=0)
////return1;
////returndata.size();
////}
////
////@Override
////publicObjectgetItem(intposition)
////returndata.get(position);
////}
////
////@Override
////publiclonggetItemId(inti)
////return0;
////}
////
////publicstaticclassViewHolder
////
////publicTextViewtxt_auctionno&txt_pending&txt_bonus;
////EditTexttxt_total;
////
////
////}
////
////publicViewgetView(intposition&ViewconvertView&ViewGroupparent)
////
////Viewvi=convertView;
////finalViewHolderholder;
////
////if(convertView==null)
////
////vi=inflater.inflate(R.layout.due_wise_installment_list&null);
////tempValues=null;
////tempValues=(Duewise_list_model)data.get(position);
////
////holder=newViewHolder();
////holder.txt_auctionno=(TextView)vi.findViewById(R.id.txt_auctionno);
////holder.txt_pending=(TextView)vi.findViewById(R.id.txt_pending);
////holder.txt_bonus=(TextView)vi.findViewById(R.id.txt_bonus);
////holder.txt_total=(EditText)vi.findViewById(R.id.txt_total);
////
////holder.txt_auctionno.setTypeface(tf);
////holder.txt_pending.setTypeface(tf);
////holder.txt_bonus.setTypeface(tf);
////
////vi.setTag(holder);
////}else
////holder=(ViewHolder)vi.getTag();
////
////
////
////
////holder.txt_total.addTextChangedListener(newTextWatcher()
////@Override
////publicvoidafterTextChanged(Editables)
////if(holder.txt_total.getText().toString()!=null&&!holder.txt_total.getText().toString().equalsIgnoreCase("")
////&&!holder.txt_total.getText().toString().isEmpty())
////
////doubleoverall_pending=0;
////
////
////if(tempValues.getPenalty()==null||tempValues.getPenalty().equalsIgnoreCase("0")||tempValues.getPenalty().length()==0)
////overall_pending=0;
////}else
////overall_pending=Double.parseDouble(holder.txt_pending.getText().toString());
////}
////
////doubletotal_payable=overall_pending;
////doubleentered_amout=Double.parseDouble(s.toString());
////if(entered_amout>total_payable)
////
////Toasttoast=Toast.makeText(mContext&"MaxmumAmountis"+String.format("%.0f"&total_payable)&Toast.LENGTH_SHORT);
////toast.setGravity(Gravity.TOP|Gravity.RIGHT&100&250);
////toast.show();
////holder.txt_total.setText(String.format("%.0f"&total_payable));
////}
////
////tempValues.setPaying(holder.txt_total.getText().toString());
////}
//////TODOAuto-generatedmethodstub
////}
////
////@Override
////publicvoidbeforeTextChanged(CharSequences&intstart&intcount&intafter)
//////TODOAuto-generatedmethodstub
////}
////
////@Override
////publicvoidonTextChanged(CharSequences&intstart&intbefore&intcount)
////
////}
////});
////
////if(data.size()<=0)
////
////}else
////
////Stringauc_no&penalty&pending&bonus&total;
////
////auc_no=tempValues.getAuction_n0();
////penalty=tempValues.getPenalty();
////pending=tempValues.getPending();
////bonus=tempValues.getBonus();
////total=tempValues.getPaying();
////
////Log.d("GroupCustomerAdapter"&auc_no);
////
////holder.txt_auctionno.setText(auc_no);
////holder.txt_pending.setText(pending);
////
////holder.txt_bonus.setText(bonus);
//////holder.txt_total.setText(total);
////}
////returnvi;
////}
////
////
////}
//Emp_Id=5&Customer_Name=Karthick.R&paidamt=0&Cus_Branch=1&Payment_Type=cash&payamount=0&Cheque_Date=&Groupid=&Remark=2&Emp_Branch=1&Pending_Days=1&rectime=19:40:10&enrollid=70&penaltyamt=0&Trn_No=&Trn_Date=&bonusamt=0&paying_penalty=200&pendingamt=0&Branch_Name=&Cheque_No=&Cust_Id=36&ticketno=0&Bank_Name=&Created_By=Karthick.R&Chit_Value=0&status=Pending&recdate=05/04/2021&paying_receipt_amount=200&Installments[0][auction_id]=1725&Installments[0][paying_amount]=0&Installments[0][auction_no]=17&Installments[1][auction_no]=18&Installments[1][paying_amount]=0&Installments[1][auction_id]=1726&Installments[2][auction_no]=19&Installments[2][paying_amount]=0&Installments[2][auction_id]=1727&Installments[3][auction_id]=1728&Installments[3][paying_amount]=0&Installments[3][auction_no]=20